export interface InventoryItem {
  id: string;
  name: string;
  description: string;
  quantity: number;
  minStock: number;
  location: string;
  unit?: string;
  status: string;
  acquisitionDate: string;
}

export const initialItems: InventoryItem[] = [
  { id: "100", name: "Agua Tira De Abastrecimiento", description: "Costado Derecho", quantity: 1, minStock: 1, location: "UNIDADES", unit: "UR-3", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "101", name: "Agua Tiras 50Mm", description: "Costado Derecho", quantity: 2, minStock: 1, location: "UNIDADES", unit: "UR-3", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "102", name: "Agua Gemelos", description: "Costado Derecho", quantity: 3, minStock: 1, location: "UNIDADES", unit: "UR-3", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "103", name: "Agua Copla De Grifo", description: "Costado Derecho", quantity: 2, minStock: 1, location: "UNIDADES", unit: "UR-3", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "104", name: "Agua Filtro", description: "Costado Derecho", quantity: 1, minStock: 1, location: "UNIDADES", unit: "UR-3", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "105", name: "Agua Piton Automatico", description: "Costado Derecho", quantity: 1, minStock: 1, location: "UNIDADES", unit: "UR-3", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "106", name: "Agua Piton Akron Regulable", description: "Costado Derecho", quantity: 2, minStock: 1, location: "UNIDADES", unit: "UR-3", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "107", name: "Agua Piton De Boquilla", description: "Costado Derecho", quantity: 1, minStock: 1, location: "UNIDADES", unit: "UR-3", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "108", name: "Agua Llave De Copla", description: "Costado Derecho", quantity: 3, minStock: 1, location: "UNIDADES", unit: "UR-3", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "109", name: "Agua Llave De Grifo", description: "Costado Derecho", quantity: 2, minStock: 1, location: "UNIDADES", unit: "UR-3", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "110", name: "Agua Flotador", description: "Costado Derecho", quantity: 1, minStock: 1, location: "UNIDADES", unit: "UR-3", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "111", name: "Agua Tiras De 50Mm", description: "Costado Izquierdo ", quantity: 4, minStock: 1, location: "UNIDADES", unit: "UR-3", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "112", name: "Agua Tiras De 70Mm", description: "Costado Izquierdo ", quantity: 4, minStock: 1, location: "UNIDADES", unit: "UR-3", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "113", name: "Agua Monitor De Piso", description: "Techo", quantity: 1, minStock: 1, location: "UNIDADES", unit: "UR-3", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "114", name: "Agua", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "UR-3", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "115", name: "Agua Tiras De 50Mm", description: "Techo", quantity: 14, minStock: 1, location: "UNIDADES", unit: "UR-3", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "116", name: "Agua Filtro Plano", description: "Techo", quantity: 1, minStock: 1, location: "UNIDADES", unit: "UR-3", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "117", name: "Agua Chorizo", description: "Techo", quantity: 3, minStock: 1, location: "UNIDADES", unit: "UR-3", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "118", name: "Agua Bichero", description: "Techo", quantity: 1, minStock: 1, location: "UNIDADES", unit: "UR-3", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "119", name: "Agua Mochilas C/2 Tiras De 50Mm", description: "Techo", quantity: 2, minStock: 1, location: "UNIDADES", unit: "UR-3", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "120", name: "Comunicaciones Table Lenovo", description: "Cabina ", quantity: 1, minStock: 1, location: "UNIDADES", unit: "UR-3", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "121", name: "Cabina Arnes Msa M7 4500 Psi", description: "Maquina 71 - Cabina", quantity: 4, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "122", name: "Cabina Cuña Madera Escalonada", description: "Maquina 71 - Cabina", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "123", name: "Cabina Chalecos Reflectantes", description: "Maquina 71 - Cabina", quantity: 5, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "124", name: "Cabina Medidor De Temperatura", description: "Maquina 71 - Cabina", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "125", name: "Cabina Llave De Ascensor", description: "Maquina 71 - Cabina", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "126", name: "Cabina Gre", description: "Maquina 71 - Cabina", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "127", name: "Cabina Eslingas", description: "Maquina 71 - Cabina", quantity: 3, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "128", name: "L1 Llave De Grifo", description: "Maquina 71 - L1", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "129", name: "L1 Llave De Copla Simple", description: "Maquina 71 - L1", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "130", name: "L1 Llave De Copla Doble", description: "Maquina 71 - L1", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "131", name: "L1 Traspaso 70Mm A 70Mm", description: "Maquina 71 - L1", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "132", name: "L1 Traspaso 50Mm A 70Mm", description: "Maquina 71 - L1", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "133", name: "L1 Traspaso Hilo 70Mm Grifo", description: "Maquina 71 - L1", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "134", name: "L1 Traspaso 70Mm A 110Mm", description: "Maquina 71 - L1", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "135", name: "L1 Traspaso Hilo M. A 110Mm", description: "Maquina 71 - L1", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "136", name: "L1 Traspaso Hilo H. A 110Mm", description: "Maquina 71 - L1", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "137", name: "L1 Traspaso Hilo H. A 70Mm", description: "Maquina 71 - L1", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "138", name: "L1 Traspaso 70Mm A 65Mm", description: "Maquina 71 - L1", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "139", name: "L1 Combo Goma", description: "Maquina 71 - L1", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "140", name: "L2 Bolsos Con 2 Tiras De 52Mm", description: "Maquina 71 - L2", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "141", name: "L2 52Mm Storz", description: "Maquina 71 - L2", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "142", name: "L2 Filtro Plano 70Mm Stoz", description: "Maquina 71 - L2", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "143", name: "L2 Flotador", description: "Maquina 71 - L2", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "144", name: "L2 Filtro Hilo H. 110 Mm", description: "Maquina 71 - L2", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "145", name: "L2 Baja Expansión C/Manguerin", description: "Maquina 71 - L2", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "146", name: "L2 Bidon Mescla", description: "Maquina 71 - L2", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "147", name: "L2 Caja Multiproposito", description: "Maquina 71 - L2", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "148", name: "L2 Cuña Metalica Carro", description: "Maquina 71 - L2", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "149", name: "L3 Hacha Golpe", description: "Maquina 71 - L3", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "150", name: "L3 Hacha Golpe Chica", description: "Maquina 71 - L3", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "151", name: "L3 Napoleon", description: "Maquina 71 - L3", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "152", name: "L3 Combo", description: "Maquina 71 - L3", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "153", name: "L3 T.N.T", description: "Maquina 71 - L3", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "154", name: "L3 Diablo", description: "Maquina 71 - L3", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "155", name: "L3 Roof Hook", description: "Maquina 71 - L3", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "156", name: "L3 Haligan Pata Cabra", description: "Maquina 71 - L3", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "157", name: "L3 Bolso De Altura", description: "Maquina 71 - L3", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "158", name: "L3 Extintor", description: "Maquina 71 - L3", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "159", name: "B4 Motobomba 250 Gpm", description: "Maquina 71 - B4", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "160", name: "B5 Bichero De Gancho", description: "Maquina 71 - B5", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "161", name: "B5 Chuzo", description: "Maquina 71 - B5", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "162", name: "B5 Escala Aluminio", description: "Maquina 71 - B5", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "163", name: "R4 Según Boquillas", description: "Maquina 71 - R4", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "164", name: "R4 Tft Twister", description: "Maquina 71 - R4", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "165", name: "R4 Smooth Bore 464 Gpm", description: "Maquina 71 - R4", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "166", name: "R4 Gemelo 70X50X50", description: "Maquina 71 - R4", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "167", name: "R4 Inductor En Linea", description: "Maquina 71 - R4", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "168", name: "R4 Bolso Porta Uniforme", description: "Maquina 71 - R4", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "169", name: "R4 Palillos Tiras", description: "Maquina 71 - R4", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "170", name: "R4 Conos", description: "Maquina 71 - R4", quantity: 5, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "171", name: "R3 Lona De Material", description: "Maquina 71 - R3", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "172", name: "R3 Cilindro 4500 Psi", description: "Maquina 71 - R3", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "173", name: "R3 Arnes 4500 Psi M7", description: "Maquina 71 - R3", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "174", name: "R3 Arnes 4500 Psi G1", description: "Maquina 71 - R3", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "175", name: "R3 Farol Milwaukee", description: "Maquina 71 - R3", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "176", name: "R2 Botiquín", description: "Maquina 71 - R2", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "177", name: "R1 Cuerda Utilitaria", description: "Maquina 71 - R1", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "178", name: "R1 Cadena Remolque", description: "Maquina 71 - R1", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "179", name: "Cr Cilindro 4500 Psi", description: "Maquina 71 - Cr", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "180", name: "Cl Tft Ultimatic", description: "Maquina 71 - Cl", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "181", name: "Cl Llave De Copla Style 10", description: "Maquina 71 - Cl", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "182", name: "Cl Paquete De Altura", description: "Maquina 71 - Cl", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "183", name: "Cl Cilindro 4500 Psi Scott", description: "Maquina 71 - Cl", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "184", name: "Parachoque 38Mm Storz", description: "Maquina 71 - Parachoque", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "185", name: "Parachoque Akron Style 1733", description: "Maquina 71 - Parachoque", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "186", name: "Parachoque 52Mm Storz", description: "Maquina 71 - Parachoque", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "187", name: "Parachoque Corte Rapido", description: "Maquina 71 - Parachoque", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "188", name: "Parachoque 70Mm Storz", description: "Maquina 71 - Parachoque", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "189", name: "Parachoque 70Mm Storz Abastecimiento", description: "Maquina 71 - Parachoque", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "190", name: "Techo Chorizo 110Mm Hilo", description: "Maquina 71 - Techo", quantity: 3, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "191", name: "Techo Chorizo 70Mm Storz", description: "Maquina 71 - Techo", quantity: 3, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "192", name: "Techo Llave Bidon Concentrado", description: "Maquina 71 - Techo", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "193", name: "Techo 70Mm Storz Monitor", description: "Maquina 71 - Techo", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "194", name: "Techo 1250 Gpm", description: "Maquina 71 - Techo", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "195", name: "Techo Concentrado Clase A", description: "Maquina 71 - Techo", quantity: 3, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "196", name: "Techo 52Mm Storz", description: "Maquina 71 - Techo", quantity: 9, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "197", name: "Techo 75Mm Storz (Amarilla)", description: "Maquina 71 - Techo", quantity: 7, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "198", name: "Techo Pala", description: "Maquina 71 - Techo", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "199", name: "Techo Cinturon Bump And Run", description: "Maquina 71 - Techo", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "200", name: "Cama Rapida 52Mm Storz", description: "Maquina 71 -  Cama Rapida", quantity: 3, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "201", name: "Cama Rapida Tft Thunderfog", description: "Maquina 71 - Cama Rapida", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-71", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "202", name: "Agua Tiras", description: "50Mm", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "203", name: "Agua Piton", description: "Tft Thunderfog ", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "204", name: "Comunicaciones Radios", description: "Motorola ", quantity: 4, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "205", name: "Comunicaciones Radios", description: "Motorola ", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "206", name: "Eras Era", description: "Msa", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "207", name: "Camara Termica", description: "Flirk ", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "208", name: "Baston Electrico", description: "Willburt", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "209", name: "Gre", description: "Gre", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "210", name: "Tablet", description: "Hotwav", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "211", name: "Iluminacion Linternas", description: "Streamlight", quantity: 5, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "212", name: "Eras Era", description: "3M", quantity: 3, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "213", name: "Eras Era", description: "Msa", quantity: 4, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "214", name: "Eras Mascaras", description: "3M", quantity: 3, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "215", name: "Eras Mascaras", description: "Msa", quantity: 4, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "216", name: "Camara Termica", description: "Isg", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "217", name: "Botiquines", description: "Botiquín Azul M72 -⁠  ⁠15 Gasas Hidrofilas Grandes. -⁠  ⁠12 Gasas No Tejidas 5X5 Cm ( 2 Por Paquete). -⁠  ⁠1 Caja De Paracetamol 500 Mg  -⁠  ⁠1 Caja De Ibuprofeno 600Mg. -⁠  ⁠1 Inhalador Salbutamol  -⁠  ⁠2 Tela Micropore -⁠  ⁠1 Tijera Curva  -⁠  ⁠1 Pinza Anatómica. -⁠  ⁠1 Cinta Adhesiva Waterproof -⁠  ⁠1 Caja De Alcohol Pads. -⁠  ⁠5 Jeringas 5Ml Aguja 21G  -⁠  ⁠1 Caja De Guantes Talla L -⁠  ⁠1 Suero Fisiológico 0.9% 1Lt. -⁠  ⁠2 Sueros Fisiológicos 0.9% 250Ml -⁠  ⁠1 Collar Cervical Adulto -⁠  ⁠1 Collar Cervical Pediátrico  -⁠  ⁠1 Válvula Unidireccional Rcp -⁠  ⁠1 Ambu Con Adaptador De Adulto Y Pediátrico  -⁠  ⁠2 Gasas Pañal -⁠  ⁠1 Venda Elástica  -⁠  ⁠1 Cabestrillo Adulto -⁠  ⁠1 Esfigno Manómetro  -⁠  ⁠1 Fonendo - Botiquín Rojo M72 Y Botiquín Rojo Ur3 ( Contienen Exactamente Lo Mismo) -⁠  ⁠1 Collar Cervical Adulto -⁠  ⁠10 Gasas Hidrofilas Grandes. -⁠  ⁠12 Gasas No Tejidas 5X5 Cm (2 Por Paquete) -⁠  ⁠20 Alcohol Pads -⁠  ⁠20 Parche Curita -⁠  ⁠5 Jeringas 5Ml Aguja 21G  -⁠  ⁠2 Vendas Gasa Eslaticada ( Elastomull) -⁠  ⁠1 Vendaje Triangular  -⁠  ⁠2 Sueros Fisiológicos 0.9% 250Ml -⁠  ⁠1 Caja Paracetamol 500Mg -⁠  ⁠1 Caja Ibuprofeno 600Mg -⁠  ⁠1 Inhalador Salbutamol  -⁠  ⁠1 Agua Oxigenada  -⁠  ⁠1 Tijera Curva  -⁠  ⁠1 Pinza Anatómica  -⁠  ⁠1 Manta Térmica ", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "218", name: "Chalecos Reflectantes", description: "", quantity: 5, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "219", name: "Chaleco Ci", description: "", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "220", name: "Rescate Arnes", description: "", quantity: 4, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "221", name: "Rescate Tabla Adulto", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "222", name: "Rescate Pulpo", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "223", name: "Herramientas Bolsos", description: "", quantity: 3, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "224", name: "Agua Tiras", description: "50Mm", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "225", name: "Agua Tiras Abastecimiento", description: "70Mm", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "226", name: "Lona", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "227", name: "Combustible Bidon De Mezcla", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "228", name: "Cinta Peligro", description: "", quantity: 3, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "229", name: "Agua Traspaso", description: "70-50Mm", quantity: 4, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "230", name: "Agua Traspaso Municipal", description: "70-65Mm", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "231", name: "Agua Siames", description: "70-70Mm", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "232", name: "Agua Gemelo", description: "70-50Mm", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "233", name: "Agua Llave De Grifo", description: "", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "234", name: "Agua Llave De Copla", description: "", quantity: 4, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "235", name: "Agua Llave De Matriz", description: "", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "236", name: "Agua Combo De Goma", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "237", name: "Agua Boquilla", description: "1 \"1/8\"", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "238", name: "Agua Traspaso Manifor", description: "Hilo Hembra 110", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "239", name: "Aire Ventilador", description: "Tempest", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "240", name: "Electronico Generador", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "241", name: "Iluminacion Enchufe Industrial", description: "Eisen 3150Ie", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "242", name: "Agua Bolsos De Herramientas", description: "Bolso N°1:   1Esmeril, 2 Baterías,  2 Discos De Cambio  Bolso N°2  1  Esmeril, 1 Batería, Destornilladores Y Llaves Del 14 Y 11    ", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "243", name: "Corte Moto Amoledora", description: "Husqvarna K970 Rescue", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "244", name: "Corte Motosierra", description: "Tempest Ventmaster", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "245", name: "Iluminacion Carrete Extensor", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "246", name: "Seguridad  Conos", description: "", quantity: 7, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "247", name: "Embudo", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "248", name: "Iluminacion Foco", description: "Akron ", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "249", name: "Seguridad  Extintor", description: "Pqs", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "250", name: "Entrada Forzada Hacha De Golpe", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "251", name: "Entrada Forzada Roofhook", description: "", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "252", name: "Entrada Forzada Combo", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "253", name: "Entrada Forzada Halligan De Corte", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "254", name: "Entrada Forzada Napoleon", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "255", name: "Entrada Forzada Simon 8", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "256", name: "Entrada Forzada Diablo", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "257", name: "Combustible  Bencina", description: "20Lts", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "258", name: "Pala", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "259", name: "Entrada Forzada Bicheros", description: "", quantity: 3, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "260", name: "Entrada Forzada Roofhook", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "261", name: "Entrada Forzada Bichero 2 Puntas", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "262", name: "Entrada Forzada Bichero Rastrillo", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "263", name: "Agua Chorizos", description: "125Mm", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "264", name: "Eras Cilindro Recambio", description: "", quantity: 16, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "265", name: "Uniformes  Bolsos De Unifome", description: "", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "266", name: "Rescate Rit Pack", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "267", name: "Comunicaciones Maleta De Comunicaciones", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "268", name: "Bolsos Izamiento  Cuerda C/ Polea", description: "50Mts", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "269", name: "Bolso Normal  Cuerda", description: "50Mts", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "270", name: "Iluminacion  Focos Iluminacion", description: "Chicos ", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "271", name: "Iluminacion  Focos Iluminacion", description: "Grande", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "272", name: "Altura Bolsos De Altura", description: "Bolso 1 - R2 7 Cuñas 2 Anclas De Tira 1 Pitón Boquillas 1 Gemelo 70-50  Traspaso 70 A 50 2 Llaves De Copla Simples 1 Autofrenante Petzel - Bolso 2 R2 1 Bresnnan  1 Cinta Tubular  1 Taladro Más 2 Baterías 1 Ancla De Tira 1 Polea Para Izamiento De Material", quantity: 3, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "273", name: "Agua Flow Below Nozzle", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "274", name: "Agua Brezznan", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "275", name: "Agua Pircing Nozzle", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "276", name: "Agua Piton Autos", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "277", name: "Agua Paquetes De Altura", description: "50Mm", quantity: 4, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "278", name: "Agua Paquetes De Altura", description: "70Mm", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "279", name: "Iluminacion  Focos", description: "Grandes", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "280", name: "Eras Msa", description: "M7", quantity: 4, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "281", name: "Iluminacion Carrete Extensor", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "282", name: "Entrada Forzada Matrimonio", description: "Halligan - Hacha Golpe", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "283", name: "Eras Cilindro Recambio", description: "-", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "284", name: "Eras Cilindro Recambio", description: "-", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "285", name: "Eras Cilindro Recambio", description: "-", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "286", name: "Agua Chorizo 6 Nh", description: "", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "287", name: "Agua Piton Void", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "288", name: "Rescate Cascos", description: "", quantity: 4, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "289", name: "Rescate Tripode", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "290", name: "Rescate Bolsos 100 Mts Cuerdas", description: "", quantity: 4, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "291", name: "Rescate Bolsos 50Mts Cuerdas", description: "", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "292", name: "Rescate Bolso 55 Mts Cuerda Utilitaria", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "293", name: "Rescate Bolsos Con Arnes", description: "", quantity: 3, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "294", name: "Rescate Bolso Sistema Polea Tripode", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "295", name: "Rescate Bolso 4 Eslingas", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "296", name: "Rescate Bolso Con Cintas", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "297", name: "Rescate Bolso Con Poleas", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "298", name: "Agua Tiras 70 Mm", description: "", quantity: 8, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "299", name: "Agua Tiras 70 Mm", description: "", quantity: 9, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "300", name: "Agua Tiras 70 Mm", description: "", quantity: 6, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "301", name: "Agua Minute Man (4 Tiras 50 + Piton)", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "302", name: "Agua Minute Man (4 Tiras 50 + Piton)", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "303", name: "Zapa Pala", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "304", name: "Agua Dados De Matriz", description: "", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "305", name: "Agua Ganchos Levanta Tapas Matriz", description: "", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "306", name: "Zapa Bichero Con Puntas", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "307", name: "Zapa Bichero Rastrillo", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "308", name: "Zapa Roofhook", description: "", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "309", name: "Zapa Halligan Pata Cabra", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "310", name: "Zapa Bicheros", description: "", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "311", name: "Rescate Cubre Canto", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "312", name: "Rescate Camilla Sketch", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "313", name: "Espuma Bidones Concentrado", description: "", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "314", name: "Agua Filtro 110 Mm", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "315", name: "Espuma Piton Baja Expansion", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "316", name: "Espuma Eductor Con Manguerin", description: "", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "317", name: "Agua Chorizo 6 Nh", description: "Maquina 72 - Back", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "318", name: "Comunicaciones Radios Motorola Dgp 8550E", description: "Maquina 72 - Cabina", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "319", name: "Comunicaciones Micrófonos Motola", description: "Maquina 72 - Cabina", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "320", name: "Seguridad Botiquin", description: "Maquina 72 - Cabina", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "321", name: "Eras Arnes 4500 Psi M7 C/Mascara", description: "Maquina 72 - Cabina", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "322", name: "Eras Arnes 4500 Psi Scott C/ Maascara", description: "Maquina 72 - Cabina", quantity: 3, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "323", name: "Seguridad Chalecos Reflectantes", description: "Maquina 72 - Cabina", quantity: 5, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "324", name: "Eras Mascaras Msa", description: "Maquina 72 - Cabina", quantity: 6, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "325", name: "Rescate Arnes", description: "Maquina 72 - Cabina", quantity: 4, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "326", name: "Seguridad Gre", description: "Maquina 72 - Cabina", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "327", name: "Electronico Camara Termica", description: "Maquina 72 - Cabina", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "328", name: "Electronico Tiff", description: "Maquina 72 - Cabina", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "329", name: "Electronico Termometro", description: "Maquina 72 - Cabina", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "330", name: "Electronico Anemometro", description: "Maquina 72 - Cabina", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "331", name: "Herramientas Llave De Ascensor", description: "Maquina 72 - Cabina", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "332", name: "Herramientas Corta Cinturon", description: "Maquina 72 - Cabina", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "333", name: "Electronico Baston", description: "Maquina 72 - Cabina ", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "334", name: "Linternas Linternas", description: "Maquina 72 - Cabina ", quantity: 6, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "335", name: "Cargador Multicargador Motorola", description: "Maquina 72 - Cabina ", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "336", name: "Comunicaciones Radios Motorola R2 C/ Microfono", description: "Maquina 72 - Cabina ", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "337", name: "Comunicaciones Radio Motorola 350 Mx", description: "Maquina 72 - Cabina ", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "338", name: "Agua Piton Void", description: "Maquina 72 - Cajonera Techo", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "339", name: "Rescate Cascos", description: "Maquina 72 - Cajonera Techo", quantity: 4, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "340", name: "Rescate Tripode", description: "Maquina 72 - Cajonera Techo", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "341", name: "Rescate Bolsos 100 Mts Cuerdas", description: "Maquina 72 - Cajonera Techo", quantity: 4, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "342", name: "Rescate Bolsos 50Mts Cuerdas", description: "Maquina 72 - Cajonera Techo", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "343", name: "Rescate Bolso 55 Mts Cuerda Utilitaria", description: "Maquina 72 - Cajonera Techo", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "344", name: "Rescate Bolsos Con Arnes", description: "Maquina 72 - Cajonera Techo", quantity: 3, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "345", name: "Rescate Bolso Sistema Polea Tripode", description: "Maquina 72 - Cajonera Techo", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "346", name: "Rescate Bolso 4 Eslingas", description: "Maquina 72 - Cajonera Techo", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "347", name: "Rescate Bolso Con Cintas", description: "Maquina 72 - Cajonera Techo", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "348", name: "Rescate Bolso Con Poleas", description: "Maquina 72 - Cajonera Techo", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "349", name: "Agua Tiras 70 Mm", description: "Maquina 72 - Cama C. Dercho.", quantity: 8, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "350", name: "Agua Tiras 70 Mm", description: "Maquina 72 - Cama C. Izq", quantity: 9, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "351", name: "Agua Tiras 70 Mm", description: "Maquina 72 - Cama Centro", quantity: 6, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "352", name: "Eras Cilindro Msa", description: "Maquina 72 - Cl", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "353", name: "Eras Cilindros Msa", description: "Maquina 72 - Cr", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "354", name: "Agua Minute Man (4 Tiras 50 + Piton)", description: "Maquina 72 - Crosslay L", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "355", name: "Agua Minute Man (4 Tiras 50 + Piton)", description: "Maquina 72 - Crosslay R", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "356", name: "Zapa Bolso Con Esmeril Y Accesorios", description: "Maquina 72 - L1", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "357", name: "Seguridad Cinta De Peligro", description: "Maquina 72 - L1", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "358", name: "Agua Tiras De 50 Mm", description: "Maquina 72 - L1", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "359", name: "Motores Ventilador", description: "Maquina 72 - L1", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "360", name: "Motores Generador (Inverter)", description: "Maquina 72 - L1", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "361", name: "Herramientas Llave De Grifo", description: "Maquina 72 - L1", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "362", name: "Herramientas Llaves De Copla Simple", description: "Maquina 72 - L1", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "363", name: "Motores Bidon Bencina 20 Lts", description: "Maquina 72 - L1", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "364", name: "Agua Traspaso Grifo", description: "Maquina 72 - L1", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "365", name: "Motores Bidon Mezcla", description: "Maquina 72 - L1", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "366", name: "Agua Gemelo 70/50", description: "Maquina 72 - L1", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "367", name: "Agua Traspaso 70/50", description: "Maquina 72 - L1", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "368", name: "Agua Piton Automatico", description: "Maquina 72 - L1", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "369", name: "Agua Traspaso 70/110", description: "Maquina 72 - L1", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "370", name: "Agua Traspaso 110 Hilo Hembra", description: "Maquina 72 - L1", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "371", name: "Agua Tira 70 Mm Abastecimiento", description: "Maquina 72 - L1", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "372", name: "Agua Siames 70/110", description: "Maquina 72 - L1", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "373", name: "Herramientas Bolso Herramientas", description: "Maquina 72 - L1", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "374", name: "Herramientas Llaves De Copla Doble", description: "Maquina 72 - L1", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "375", name: "Herramientas Llave De Compla Simple", description: "Maquina 72 - L1", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "376", name: "Herramientas Combo De Goma", description: "Maquina 72 - L1", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "377", name: "Agua Llave De Grifo", description: "Maquina 72 - L1", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "378", name: "Agua Traspaso 65/70", description: "Maquina 72 - L1", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "379", name: "Agua Traspaso 70 Grifo", description: "Maquina 72 - L1", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "380", name: "Motores Motosierra", description: "Maquina 72 - L2", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "381", name: "Motores Motoamoladora", description: "Maquina 72 - L2", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "382", name: "Seguridad Extintor", description: "Maquina 72 - L2", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "383", name: "Seguridad Foco Con Pedestal", description: "Maquina 72 - L2", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "384", name: "Seguridad Conos Naranjos", description: "Maquina 72 - L2", quantity: 7, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "385", name: "Otros Lona", description: "Maquina 72 - L2", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "386", name: "Zapa Haligan Pata De Cabra", description: "Maquina 72 - L3", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "387", name: "Zapa Diablo", description: "Maquina 72 - L3", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "388", name: "Zapa Simon 8", description: "Maquina 72 - L3", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "389", name: "Zapa Combo", description: "Maquina 72 - L3", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "390", name: "Zapa Hacha Golpe", description: "Maquina 72 - L3", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "391", name: "Zapa Napoleon", description: "Maquina 72 - L3", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "392", name: "Agua Tiras De 50 Mm + Piton", description: "Maquina 72 - Parachoque", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "393", name: "Eras Msa S/ Mascara", description: "Maquina 72 - R1", quantity: 6, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "394", name: "Eras Cilindros Msa", description: "Maquina 72 - R1", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "395", name: "Agua Pitón Autos Eléctricos", description: "Maquina 72 - R2", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "396", name: "Seguridad Foco Con Pedestal", description: "Maquina 72 - R2", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "397", name: "Agua Bolsos De Erramientas", description: "Maquina 72 - L1", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "398", name: "Agua Bolsos De Altura", description: "Maquina 72 - R2", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "399", name: "Agua Paquetes De Altura", description: "Maquina 72 - R2", quantity: 4, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "400", name: "Seguridad Farol", description: "Maquina 72 - R2", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "401", name: "Cuerdas Bolso Con Cuerda Utilitaria", description: "Maquina 72 - R2", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "402", name: "Rescate Bolso Rit", description: "Maquina 72 - R2", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "403", name: "Zapa Matrimonio", description: "Maquina 72 - R2", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "404", name: "Agua Piton Floor Below Noozle", description: "Maquina 72 - R2", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "405", name: "Electronico Dea", description: "Maquina 72 - R3", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "406", name: "Seguridad Botiquin", description: "Maquina 72 - R3", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "407", name: "Seguridad Cuñas Escalonadas", description: "Maquina 72 - R3", quantity: 4, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "408", name: "Eras Cilindros Msa", description: "Maquina 72 - R3", quantity: 4, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "409", name: "Eras Cilindros Scott", description: "Maquina 72 - R3", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "410", name: "Epp Bolsos Porta Uniforme", description: "Maquina 72 - R3", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "411", name: "Comunicaciones Maleta Comunicaciones", description: "Maquina 72 - R3", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "412", name: "Zapa Pala", description: "Maquina 72 - Techo", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "413", name: "Agua Dados De Matriz", description: "Maquina 72 - Techo", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "414", name: "Agua Ganchos Levanta Tapas Matriz", description: "Maquina 72 - Techo", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "415", name: "Zapa Bichero Con Puntas", description: "Maquina 72 - Techo", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "416", name: "Zapa Bichero Rastrillo", description: "Maquina 72 - Techo", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "417", name: "Zapa Roofhook", description: "Maquina 72 - Techo", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "418", name: "Zapa Halligan Pata Cabra", description: "Maquina 72 - Techo", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "419", name: "Zapa Bicheros", description: "Maquina 72 - Techo", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "420", name: "Rescate Cubre Canto", description: "Maquina 72 - Techo", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "421", name: "Rescate Camilla Sketch", description: "Maquina 72 - Techo", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "422", name: "Espuma Bidones Concentrado", description: "Maquina 72 - Techo", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "423", name: "Agua Filtro 110 Mm", description: "Maquina 72 - Techo", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "424", name: "Espuma Piton Baja Expansion", description: "Maquina 72 - Techo", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "425", name: "Espuma Eductor Con Manguerin", description: "Maquina 72 - Techo", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-72", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "426", name: "Tiras 52Mm Storz", description: "Maquina 73 - Costado Derecho", quantity: 3, minStock: 1, location: "UNIDADES", unit: "M-73", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "427", name: "Tiras 70Mm Storz", description: "Maquina 73 - Costado Derecho", quantity: 4, minStock: 1, location: "UNIDADES", unit: "M-73", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "428", name: "Tiras 70Mm Storz Abastecimiento", description: "Maquina 73 - Costado Derecho", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-73", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "429", name: "Motores Motobomba Homelite", description: "Maquina 73 - Costado Derecho", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-73", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "430", name: "Agua Traspaso 70Mm A 70Mm", description: "Maquina 73 - Costado Derecho", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-73", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "431", name: "Agua Traspaso 70Mm A 110Mm", description: "Maquina 73 - Costado Derecho", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-73", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "432", name: "Agua Traspaso 110Mm A 110Mm", description: "Maquina 73 - Costado Derecho", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-73", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "433", name: "Agua Flotador", description: "Maquina 73 - Costado Izquierdo", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-73", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "434", name: "Agua Traspaso 70Mm A 110Mm", description: "Maquina 73 - Costado Izquierdo", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-73", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "435", name: "Agua Traspaso 110Mm A 110Mm", description: "Maquina 73 - Costado Izquierdo", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-73", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "436", name: "Agua Llave De Grifo", description: "Maquina 73 - Costado Izquierdo", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-73", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "437", name: "Agua Llave De Copla Simple", description: "Maquina 73 - Costado Izquierdo", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-73", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "438", name: "Agua Traspaso 70Mm A 70Mm", description: "Maquina 73 - Costado Izquierdo", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-73", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "439", name: "Agua Traspaso Hilo 70Mm Grifo", description: "Maquina 73 - Costado Izquierdo", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-73", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "440", name: "Agua Traspaso 50Mm A 70Mm", description: "Maquina 73 - Costado Izquierdo", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-73", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "441", name: "Agua Cifon 110Mm 52Mm", description: "Maquina 73 - Costado Izquierdo", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-73", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "442", name: "Agua Filtro Plano 70Mm Stoz", description: "Maquina 73 - Costado Izquierdo", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-73", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "443", name: "Agua Filtro Plano 110Mm Storz", description: "Maquina 73 - Costado Izquierdo", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-73", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "444", name: "Seguridad Cuña Metalica", description: "Maquina 73 - Costado Izquierdo", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-73", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "445", name: "Piton Akron Style 1769", description: "Maquina 73 - Costado Izquierdo", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-73", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "446", name: "Agua Codo Piscina", description: "Maquina 73 - Costado Izquierdo", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-73", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "447", name: "Seguridad Conos Retractiles", description: "Maquina 73 - Costado Izquierdo", quantity: 3, minStock: 1, location: "UNIDADES", unit: "M-73", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "448", name: "Zapa Napoleon", description: "Maquina 73 - Costado Izquierdo", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-73", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "449", name: "Agua Trifurca", description: "Maquina 73 - Costado Izquierdo", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-73", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "450", name: "Piton 350 Gpm", description: "Maquina 73 - Parachoque Del", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-73", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "451", name: "Seguridad Lona Piscina", description: "Maquina 73 - Parachoque", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-73", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "452", name: "Agua Piscina", description: "Maquina 73 - Parachoque", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-73", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "453", name: "Tiras Chorizo 110Mm Storz", description: "Maquina 73 - Parachoque", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-73", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "454", name: "Tiras Chorizo 70Mm Storz", description: "Maquina 73 - Parachoque", quantity: 2, minStock: 1, location: "UNIDADES", unit: "M-73", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "455", name: "Agua Traspaso 110Mm A 110Mm", description: "Maquina 73 - Parachoque", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-73", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "456", name: "Agua Traspaso 70Mm A 110Mm", description: "Maquina 73 - Parachoque", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-73", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "457", name: "Seguridad Gre", description: "Maquina 73 - Cabina", quantity: 1, minStock: 1, location: "UNIDADES", unit: "M-73", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "458", name: "Zapa Pala", description: "Bodega 1", quantity: 6, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "459", name: "Zapa Mango Pala", description: "Bodega 1", quantity: 2, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "460", name: "Tiras Chorizo 110Mm Storz", description: "Bodega 1", quantity: 4, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "461", name: "Tiras Chorizo 70Mm Storz", description: "Bodega 1", quantity: 2, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "462", name: "Tiras Chorizo 70Mm Hilo", description: "Bodega 1", quantity: 2, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "463", name: "Seguridad Extintor", description: "Bodega 1", quantity: 6, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "464", name: "Agua Traspaso Hilo H. A 110Mm", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "465", name: "Agua Traspaso Hilo M. A 110Mm", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "466", name: "Agua Traspaso Hilo H. A 70Mm", description: "Bodega 1", quantity: 3, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "467", name: "Agua Traspaso 50Mm A 25Mm", description: "Bodega 1", quantity: 2, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "468", name: "Agua Traspaso Hilo H. 50Mm", description: "Bodega 1", quantity: 2, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "469", name: "Agua Traspaso 50Mm A 32Mm", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "470", name: "Agua Traspaso 70Mm A 70Mm", description: "Bodega 1", quantity: 3, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "471", name: "Agua Traspaso 70Mm A 38Mm", description: "Bodega 1", quantity: 2, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "472", name: "Tiras Copla 50Mm Storz", description: "Bodega 1", quantity: 10, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "473", name: "Tiras Copla 70Mm Storz", description: "Bodega 1", quantity: 4, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "474", name: "Piton 95 A 200 Gpm", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "475", name: "Piton 125 A 250 Gpm", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "476", name: "Piton Cachota", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "477", name: "Agua Ancla De Tira", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "478", name: "Zapa Roof Hook Largo", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "479", name: "Zapa Tnt", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "480", name: "Agua Llave De Grifo", description: "Bodega 1", quantity: 4, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "481", name: "Agua Llave De Copla Style 10", description: "Bodega 1", quantity: 7, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "482", name: "Agua Llave De Copla Simple", description: "Bodega 1", quantity: 5, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "483", name: "Agua Llave De Copla Doble", description: "Bodega 1", quantity: 2, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "484", name: "Zapa Diablo", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "485", name: "Agua Llave De Piso", description: "Bodega 1", quantity: 2, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "486", name: "Boquillas Corrector De Flujo Elkhart 2\"", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "487", name: "Boquillas Corrector De Flujo Elkhart 1 3/4\"", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "488", name: "Boquillas Corrector De Flujo Elkhart 1 1/2\"", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "489", name: "Boquillas Corrector De Flujo Elkhart 1 1/8\"", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "490", name: "Boquillas Corrector De Flujo Elkhart 1 3/8\"", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "491", name: "Boquillas Corrector De Flujo Akron 2\"", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "492", name: "Boquillas Corrector De Flujo Akron 1 3/4\"", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "493", name: "Boquillas Corrector De Flujo Akron 1 1/2\"", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "494", name: "Boquillas Corrector De Flujo Tft 7/8\"", description: "Bodega 1", quantity: 2, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "495", name: "Agua Filtro 70Mm", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "496", name: "Agua Filtro 110Mm", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "497", name: "Rescate Cuerda Elastica 50Mm", description: "Bodega 1", quantity: 2, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "498", name: "Rescate Cuerda Utilitaria Blanca", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "499", name: "Rescate Cuerda Utilitaria Azul", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "500", name: "Rescate Bolso Rit (Era Scott, Cuerda Y Cinta)", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "501", name: "Rescate Bolso Cuerda Utilitaria", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "502", name: "Agua Monitor De Piso", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "503", name: "Agua Filtro Plano 110 / Nuevo", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "504", name: "Agua Eductor", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "505", name: "Zapa Rastrillo", description: "Bodega 1", quantity: 6, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "506", name: "Eras Cilindros Scott 2216", description: "Bodega 1", quantity: 3, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "507", name: "Electricidad Carretes Alargadores", description: "Bodega 1", quantity: 4, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "508", name: "Electricidad Parlantes (Sirena)", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "509", name: "Electricidad Parlantes (Sirena)", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "510", name: "Electricidad Claxon", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "511", name: "Zapa Bichero 1,80 Mts", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "512", name: "Zapa Hacha De Pico", description: "Bodega 1", quantity: 2, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "513", name: "Zapa Halligan Corta Latas", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "514", name: "Zapa Roof Hook Corto", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "515", name: "Camelback Camelback", description: "Bodega 1", quantity: 10, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "516", name: "Agua Gemelo 70X70X70", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "517", name: "Agua Traspaso 110 A 70", description: "Bodega 1", quantity: 2, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "518", name: "Agua Traspaso 110 A 110", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "519", name: "Agua Traspaso 110 A Hilo Macho", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "520", name: "Agua Traspaso 70 A Hilo Hembra", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "521", name: "Agua Tiras De 50Mm Cortas", description: "Bodega 1", quantity: 2, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "522", name: "Agua Traspasos De 6Nh A 110 Storz", description: "Bodega 1", quantity: 3, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "523", name: "Agua Tapas 110 Storz", description: "Bodega 1", quantity: 3, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "524", name: "Agua Tapas 70 Storz", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "525", name: "Agua Traspaso De 50Mm A 70Mm", description: "Bodega 1", quantity: 6, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "526", name: "Agua Traspaso De 70Mm A 65Mm", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "527", name: "Electricidad Focos Frc", description: "Bodega 1", quantity: 2, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "528", name: "Rescate Canasto Rojo", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "529", name: "Rescate Tabla Espinal Adulto", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "530", name: "Rescate Tabla Espinal Pediatrica", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "531", name: "Rescate Pulpo", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "532", name: "Rescate Asiento Flamefighter", description: "Bodega 1", quantity: 1, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "533", name: "Electricidad Cargadores Milwuakee", description: "Bodega 1", quantity: 2, minStock: 1, location: "BODEGA_SUPERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "534", name: "Tiras Tira De 50Mm Rojas", description: "Bodega 2", quantity: 5, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "535", name: "Tiras Tira De 50Mm Amarillas", description: "Bodega 2", quantity: 13, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "536", name: "Tiras Tira De 38Mm Naranja", description: "Bodega 2", quantity: 1, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "537", name: "Tiras Tira De 38Mm Blanca", description: "Bodega 2", quantity: 1, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "538", name: "Tiras Tira De 70 Roja Goma", description: "Bodega 2", quantity: 3, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "539", name: "Tiras Tira De 52 Amarilla Goma", description: "Bodega 2", quantity: 2, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "540", name: "Tiras Tira De 70Mm Rojas", description: "Bodega 2", quantity: 16, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "541", name: "Motores Motosierra", description: "Bodega 2", quantity: 1, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "542", name: "Motores Pulverizador", description: "Bodega 2", quantity: 2, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "543", name: "Seguridad Conos", description: "Bodega 2", quantity: 3, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "544", name: "Motores Motobomba", description: "Bodega 2", quantity: 2, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "545", name: "Motores Bidon Bencina 20 Lts", description: "Bodega 2", quantity: 5, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "546", name: "Seguridad Cuerda Utilitaria", description: "Bodega 2", quantity: 2, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "547", name: "Mantenimiento Cooler Rojo", description: "Bodega 2", quantity: 1, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "548", name: "Mantenimiento Caja Herramientas 1", description: "Bodega 2", quantity: 1, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "549", name: "Mantenimiento Caja Herramientas 2", description: "Bodega 2", quantity: 1, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "550", name: "Mantenimiento Caja Herramientas 3", description: "Bodega 2", quantity: 1, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "551", name: "Mantenimiento Caja Herramientas 4", description: "Bodega 2", quantity: 1, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "552", name: "Mantenimiento Caja Herramientas 5", description: "Bodega 2", quantity: 1, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "553", name: "Seguridad Extintor 50 Segundos", description: "Bodega 2", quantity: 5, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "554", name: "Seguridad Extintor 100 Segundos", description: "Bodega 2", quantity: 5, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "555", name: "Mantenimiento Cables Para Puente", description: "Bodega 2", quantity: 1, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "556", name: "Pitones Mochila De Espaldas", description: "Bodega 2", quantity: 2, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "557", name: "Zapa Hachas", description: "Bodega 2", quantity: 2, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "558", name: "Zapa Bichero", description: "Bodega 2", quantity: 1, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "559", name: "Zapa Palas", description: "Bodega 2", quantity: 2, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "560", name: "Mantenimiento Neumaticos De Repuesto", description: "Bodega 2 - Detrás Bodega 2", quantity: 2, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "561", name: "Mantenimiento Neumatico De Repuesto", description: "Bodega 2 - Detrás Bodega 2", quantity: 1, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "562", name: "Mantenimiento Neumatico De Repuesto", description: "Bodega 2 - Detrás Bodega 2", quantity: 1, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "563", name: "Motores Soplador De Espalda", description: "Bodega 2", quantity: 2, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "564", name: "Escalas Escala Fibra 2 Cuerpos", description: "Bodega 2 - Costado Bodega", quantity: 1, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "565", name: "Mantenimiento Hidrolavadora", description: "Bodega 2", quantity: 1, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "566", name: "Eras Equipo Era 2216", description: "Bodega 2", quantity: 1, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "567", name: "Iluminacion Focos De Iluminacion", description: "Bodega 2", quantity: 2, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "568", name: "Iluminacion Carretes Focos De Iluminacion", description: "Bodega 2", quantity: 2, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "569", name: "Agua Valvula De Corte Tft", description: "Bodega 2", quantity: 1, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "570", name: "Seguridad Extintor Anzul", description: "Bodega 2", quantity: 1, minStock: 1, location: "BODEGA_INFERIOR", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "571", name: "Agua Concentrado Clase A", description: "", quantity: 13, minStock: 1, location: "CUARTEL", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "572", name: "Agua Concentrado Afff", description: "", quantity: 21, minStock: 1, location: "CUARTEL", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "573", name: "Comunicaciones Equipos Radio", description: "Motorola - Dep 450", quantity: 1, minStock: 1, location: "CUARTEL", status: "NUEVO", acquisitionDate: "2024-01-01" },
  { id: "574", name: "Comunicaciones Equipos Radio", description: "Motorola - Dep550", quantity: 2, minStock: 1, location: "CUARTEL", status: "USADO", acquisitionDate: "2024-01-01" },
  { id: "575", name: "Comunicaciones Equipos Radio", description: "Motorola - R2", quantity: 2, minStock: 1, location: "CUARTEL", status: "NUEVO", acquisitionDate: "2024-01-01" },
];